import numpy as np
import pandas as pd
from dataclasses import dataclass, field
from collections import deque
from typing import Optional

from .kernel import PulsaDataChannel, PulsaInputChannel
from .kernel import pulsa_data_kernel


is_check_extrema_num = False

@dataclass
class PulsaData:
    """Convert Binance snapshots into a streaming time-price liquidity field."""
    tick_size: float = 0.01
    max_iceberg_ratio: float = field(default=2.0)

    current_len: int = 0
    _max_cube_capacity: int = 0
    _min_cube_capacity: int = 0


    _seed_cache: deque[np.ndarray] = field(default_factory=lambda: deque(maxlen=2))
    _last_p_min: Optional[int] = None


    _cube_list: deque[np.ndarray] = field(default_factory=deque)
    _p_min_tick_list: deque[int] = field(default_factory=deque)
    _cube_len_list: deque[int] = field(default_factory=deque)
    _cube_range_list: deque[int] = field(default_factory=deque)
    _current_total_frames: int = 0

    # ==========================================

    # ==========================================
    @property
    def energy_idxs(self):
        """Return the derived signed-flow channel indices used by the model."""
        return np.arange(PulsaDataChannel.active_intensity, PulsaDataChannel.flow_press_hidden + 1)

    @property
    def anchor(self):
        return 0

    @property
    def newest_energy(self) -> np.ndarray:
        """Return energy features generated by the most recent input batch."""
        frames = self._get_newest_frames(self.current_len)
        if not frames: return np.array([])
        return np.concatenate([f[0][:, self.anchor, self.energy_idxs] for f in frames], axis=0)

    @property
    def newest_data(self) -> np.ndarray:
        """Return anchor-price features generated by the latest input batch."""
        frames = self._get_newest_frames(self.current_len)
        if not frames: return np.array([])
        return np.concatenate([f[0][:, self.anchor] for f in frames], axis=0)

    def _get_newest_frames(self, length: int) -> list[tuple[np.ndarray, int]]:
        if not self._cube_list or length <= 0:
            return []

        collected = []
        rem_len = length

        for i in range(len(self._cube_list) - 1, -1, -1):
            cube = self._cube_list[i]
            offset = self._p_min_tick_list[i]

            if rem_len <= len(cube):
                collected.append((cube[-rem_len:], offset))
                break
            else:
                collected.append((cube, offset))
                rem_len -= len(cube)

        return collected[::-1]

    # ==========================================

    # ==========================================
    def load_data(self, df: pd.DataFrame, chunk_size: int = 100):
        """Transform one Binance-shaped DataFrame batch into liquidity cubes."""
        if df.empty: return


        current_data, current_p_min = self._extract_relative_matrix(df)
        if len(current_data) == 0:
            return

        self.current_len = len(current_data)
        is_first_global = (len(self._seed_cache) == 0)

        if is_first_global:
            if self.current_len < 2:
                raise ValueError("the first batch must contain at least two samples")
            self._min_cube_capacity = self.current_len
            self._max_cube_capacity = self.current_len * 2


        compute_data = self._merge_with_seed(current_data, current_p_min, is_first_global)




        if not isinstance(compute_data, np.ndarray):
            raise TypeError(
                f"compute_data must be a NumPy array, received {type(compute_data)}"
            )
        if compute_data.dtype != np.float64:
            raise TypeError(
                f"compute_data must use float64, received {compute_data.dtype}"
            )
        if compute_data.ndim != 2:
            raise ValueError(
                f"compute_data must be two-dimensional, received {compute_data.ndim}D"
            )
        if compute_data.shape[0] == 0:
            raise ValueError("compute_data cannot be empty")
        if np.any(np.isnan(compute_data)) or np.any(np.isinf(compute_data)):
            raise ValueError("compute_data contains NaN or infinite values")


        compute_data = np.ascontiguousarray(compute_data, dtype=np.float64)


        raw_cube = pulsa_data_kernel.render_liquidity_cube_integrated(compute_data, float(self.max_iceberg_ratio))


        self._restore_absolute_coordinates(raw_cube, current_p_min)


        self._update_seed_cache(raw_cube, current_data, current_p_min)


        valid_cube = self._slice_valid_cube(raw_cube, is_first_global)
        self._manage_memory(valid_cube, current_p_min)

    # ==========================================

    # ==========================================
    def _extract_relative_matrix(self, df: pd.DataFrame) -> tuple[np.ndarray, int]:
        cols = ['bid', 'ask', 'last', 'bid_vol', 'ask_vol', 'volume']
        raw_cols: dict[str, np.ndarray] = {}

        for col in cols:
            arr = df[col].to_numpy(dtype=np.float64)
            if arr.size == 0:
                return np.zeros((0, len(PulsaInputChannel)), dtype=np.float64), 0
            raw_cols[col] = arr

        out_len = len(next(iter(raw_cols.values())))
        if out_len == 0:
            return np.zeros((0, len(PulsaInputChannel)), dtype=np.float64), 0


        b_idx = np.floor(raw_cols['bid'] / self.tick_size + 0.5).astype(np.int64)
        a_idx = np.floor(raw_cols['ask'] / self.tick_size + 0.5).astype(np.int64)
        lp_idx = np.floor(raw_cols['last'] / self.tick_size + 0.5).astype(np.int64)

        if len(b_idx) == 0:
            return np.zeros((0, len(PulsaInputChannel)), dtype=np.float64), 0


        p_min_tick = int(min(b_idx.min(), a_idx.min(), lp_idx.min()))




        if getattr(self, '_last_p_min', None) is not None and len(self._seed_cache) > 0:
            seed = self._seed_cache[-1]
            seed_abs_b = seed[PulsaInputChannel.input_bid_price.value] + self._last_p_min
            seed_abs_a = seed[PulsaInputChannel.input_ask_price.value] + self._last_p_min
            seed_abs_lp = seed[PulsaInputChannel.input_trade_price.value] + self._last_p_min
            seed_min = int(min(seed_abs_b, seed_abs_a, seed_abs_lp))
            p_min_tick = min(p_min_tick, seed_min)

        if is_check_extrema_num:
            print(f"[DATA DEBUG] Raw last price (first, last): {raw_cols['last'][0]}, {raw_cols['last'][-1]} | Tick_size: {self.tick_size}")
            print(f"[DATA DEBUG] b_idx (first, last): {b_idx[0]}, {b_idx[-1]}")
            print(f"[DATA DEBUG] a_idx (first, last): {a_idx[0]}, {a_idx[-1]}")
            print(f"[DATA DEBUG] lp_idx (first, last): {lp_idx[0]}, {lp_idx[-1]}")
            print(f"[DATA DEBUG] p_min_tick: {p_min_tick}")


        data = np.zeros((out_len, len(PulsaInputChannel)), dtype=np.float64)
        data[:, PulsaInputChannel.input_bid_price.value] = (b_idx - p_min_tick).astype(np.float64)
        data[:, PulsaInputChannel.input_ask_price.value] = (a_idx - p_min_tick).astype(np.float64)
        data[:, PulsaInputChannel.input_trade_price.value] = (lp_idx - p_min_tick).astype(np.float64)

        data[:, PulsaInputChannel.input_bid_vol.value] = raw_cols['bid_vol']
        data[:, PulsaInputChannel.input_ask_vol.value] = raw_cols['ask_vol']
        data[:, PulsaInputChannel.input_total_vol.value] = raw_cols['volume']

        return data, p_min_tick

    def _merge_with_seed(self, current_data: np.ndarray, current_p_min: int, is_first_global: bool) -> np.ndarray:
        if is_first_global:
            return current_data


        seed_row = self._seed_cache[-1].copy()


        coordinate_shift = float(self._last_p_min - current_p_min)
        if is_check_extrema_num:
            print(f"[DATA DEBUG _merge_with_seed] _last_p_min: {self._last_p_min}, current_p_min: {current_p_min}, shift: {coordinate_shift}")
            print(f"[DATA DEBUG _merge_with_seed] seed_row BEFORE shift (trade_price_idx input): {seed_row[PulsaInputChannel.input_trade_price.value]}")

        seed_row[PulsaInputChannel.input_bid_price.value] += coordinate_shift
        seed_row[PulsaInputChannel.input_ask_price.value] += coordinate_shift
        seed_row[PulsaInputChannel.input_trade_price.value] += coordinate_shift

        if is_check_extrema_num:
            print(f"[DATA DEBUG _merge_with_seed] seed_row AFTER shift (trade_price_idx input): {seed_row[PulsaInputChannel.input_trade_price.value]}")


        return np.vstack([seed_row, current_data])

    def _restore_absolute_coordinates(self, raw_cube: np.ndarray, current_p_min: int):
        if is_check_extrema_num:
            print(f"[DATA DEBUG restore] >>> START RESTORE. Adding current_p_min={current_p_min} to price channels.")

        for ch_name in dir(PulsaDataChannel):
            if ch_name.endswith('_price_idx') or ch_name == 'trade_price_idx':
                ch_val = getattr(PulsaDataChannel, ch_name)
                ch_idx = ch_val.value if hasattr(ch_val, 'value') else ch_val

                if is_check_extrema_num and raw_cube.size > 0:
                    try:
                        val_before = raw_cube[0, 0, ch_idx]
                        print(f"[DATA DEBUG restore] {ch_name} (idx {ch_idx}): {val_before} -> {val_before + float(current_p_min)}")
                    except Exception as e:
                        pass

                raw_cube[:, :, ch_idx] += float(current_p_min)

    def _update_seed_cache(self, raw_cube: np.ndarray, current_data: np.ndarray, current_p_min: int):
        for row in current_data[-2:]:
            self._seed_cache.append(row.copy())

        self._last_p_min = current_p_min

    def _slice_valid_cube(self, raw_cube: np.ndarray, is_first_global: bool) -> np.ndarray:
        if is_first_global:
            return raw_cube




        if raw_cube.shape[0] == 1:
            return raw_cube
        else:
            return raw_cube[1:]

    def _manage_memory(self, valid_cube: np.ndarray, p_min_tick: int):
        self._cube_list.append(valid_cube)
        self._p_min_tick_list.append(p_min_tick)
        self._cube_len_list.append(valid_cube.shape[0])
        self._cube_range_list.append(valid_cube.shape[1])
        self._current_total_frames += valid_cube.shape[0]


        if self._current_total_frames > self._max_cube_capacity:
            while self._current_total_frames > self._min_cube_capacity and len(self._cube_list) > 1:
                oldest_cube = self._cube_list.popleft()
                self._p_min_tick_list.popleft()
                self._cube_len_list.popleft()
                self._cube_range_list.popleft()
                self._current_total_frames -= oldest_cube.shape[0]

    # ==========================================

    # ==========================================
    def _snapshot_state(self) -> dict:
        return {
            'current_len': int(self.current_len),
            '_max_cube_capacity': int(self._max_cube_capacity),
            '_min_cube_capacity': int(self._min_cube_capacity),
            '_seed_cache': deque([row.copy() for row in self._seed_cache], maxlen=2),
            '_last_p_min': getattr(self, '_last_p_min', None),
            '_cube_list': list(self._cube_list),
            '_p_min_tick_list': list(self._p_min_tick_list),
            '_cube_len_list': list(self._cube_len_list),
            '_cube_range_list': list(self._cube_range_list),
            '_current_total_frames': int(self._current_total_frames),
        }

    def _restore_state(self, state: dict) -> None:
        self.current_len = int(state['current_len'])
        self._max_cube_capacity = int(state['_max_cube_capacity'])
        self._min_cube_capacity = int(state['_min_cube_capacity'])


        old_seed = state.get('_len1_seed_cache', state.get('_seed_vector_cache', None))
        if '_seed_cache' in state:
            self._seed_cache = deque(state['_seed_cache'], maxlen=2)
        elif old_seed is not None:
            self._seed_cache = deque([old_seed], maxlen=2)
        else:
            self._seed_cache = deque(maxlen=2)

        last_p_min = state.get('_last_p_min', None)
        if last_p_min is None:
            if hasattr(self, '_last_p_min'):
                delattr(self, '_last_p_min')
        else:
            self._last_p_min = last_p_min

        self._cube_list = deque(state['_cube_list'])
        self._p_min_tick_list = deque(state['_p_min_tick_list'])
        self._cube_len_list = deque(state['_cube_len_list'])
        self._cube_range_list = deque(state['_cube_range_list'])
        self._current_total_frames = int(state['_current_total_frames'])

    # ==========================================

    # ==========================================
    @property
    def cube_price_offsets(self) -> np.ndarray: return np.array(self._p_min_tick_list, dtype=np.uint64)
    @property
    def cubes_price_ranges(self) -> np.ndarray: return np.array(self._cube_range_list, dtype=np.uint64)
    @property
    def cube_lengths(self) -> np.ndarray: return np.array(self._cube_len_list, dtype=np.uint64)
    @property
    def cube_count(self) -> int: return len(self._cube_list)
    @property
    def cube_total_length(self) -> int: return self._current_total_frames
    @property
    def cube_channel_num(self) -> int: return len(PulsaDataChannel)
    @property
    def cube_pointers(self) -> np.ndarray:
        return np.array([c.__array_interface__['data'][0] for c in self._cube_list], dtype=np.uint64)

    def __getitem__(self, index):
        if index < 0: index += self._current_total_frames
        if index < 0 or index >= self._current_total_frames:
            raise IndexError("frame index is outside the available history")
        rem = index
        for i, length in enumerate(self._cube_len_list):
            if rem < length:
                return self._cube_list[i][rem], self._p_min_tick_list[i]
            rem -= length

    def __iter__(self):
        for cube, base_tick in zip(self._cube_list, self._p_min_tick_list):
            for frame in cube:
                yield frame, base_tick
